=== pgbackrest/pgbackrest/doc/xml/dtd/doc.dtd
<!ELEMENT doc ((description, intro, release-list, contributor-list)|(config, operation)|
               (description?, variable-list?, host-define*, block-define*, cleanup?, section+))>
    <!ATTLIST doc title CDATA #REQUIRED>
    <!ATTLIST doc subtitle CDATA "">
    <!ATTLIST doc toc CDATA "y">
    <!ATTLIST doc toc-number CDATA "y">
    <!ATTLIST doc cmd-line-len CDATA "80">

<!ELEMENT description (#PCDATA)>

<!ELEMENT intro (text)>

<!ELEMENT operation (description, text?, operation-general, command-list)>
    <!ATTLIST operation title CDATA #REQUIRED>

<!ELEMENT operation-general (option-list)>
    <!ATTLIST operation-general title CDATA #REQUIRED>

<!ELEMENT command-list (text?, command+)>
    <!ATTLIST command-list title CDATA #REQUIRED>

<!ELEMENT command (summary, text, option-list?)>
    <!ATTLIST command id CDATA #REQUIRED>
    <!ATTLIST command name CDATA #REQUIRED>

<!ELEMENT option-list (option+)>

<!ELEMENT option (summary, text, example+)>
    <!ATTLIST option id CDATA #REQUIRED>
    <!ATTLIST option section CDATA "">
    <!ATTLIST option name CDATA #REQUIRED>

<!ELEMENT config (description, text, config-section-list)>
    <!ATTLIST config title CDATA #REQUIRED>

<!ELEMENT config-example (text)>
    <!ATTLIST config-example title CDATA #REQUIRED>

<!ELEMENT config-section-list (text?, config-section+)>
    <!ATTLIST config-section-list title CDATA #REQUIRED>

<!ELEMENT config-section (text, config-key-list?)>
    <!ATTLIST config-section id CDATA #REQUIRED>
    <!ATTLIST config-section name CDATA #REQUIRED>

<!ELEMENT config-key-list (config-key+)>

<!ELEMENT config-key (summary, text, default?, allow?, example+)>
    <!ATTLIST config-key id CDATA #REQUIRED>
    <!ATTLIST config-key name CDATA #REQUIRED>

<!ELEMENT execute-list (title, execute+)>
    <!ATTLIST execute-list host CDATA #REQUIRED>
    <!ATTLIST execute-list if CDATA "">
    <!ATTLIST execute-list show CDATA "">
<!ELEMENT execute (exe-cmd, exe-cmd-extra?, exe-user?, exe-var?, exe-retry?, exe-output?, (exe-highlight-type?, exe-highlight)?,
                   exe-err-expect?, exe-err-suppress?, exe-err-suppress-stderr?)>
    <!ATTLIST execute if CDATA "">
    <!ATTLIST execute pre CDATA "">
    <!ATTLIST execute user CDATA "">
    <!ATTLIST execute filter CDATA "">
    <!ATTLIST execute filter-context CDATA "">
    <!ATTLIST execute user-force CDATA "">
    <!ATTLIST execute bash-wrap CDATA "">
    <!ATTLIST execute load-env CDATA "">
    <!ATTLIST execute skip CDATA "">
    <!ATTLIST execute show CDATA "">
    <!ATTLIST execute output CDATA "">
    <!ATTLIST execute err-suppress CDATA "">
    <!ATTLIST execute err-expect CDATA "">
    <!ATTLIST execute retry CDATA "">
    <!ATTLIST execute variable-key CDATA "">
    <!ATTLIST execute cmd-line-len CDATA "">
<!ELEMENT exe-cmd (#PCDATA)>
<!ELEMENT exe-cmd-extra (#PCDATA)>
<!ELEMENT exe-highlight (#PCDATA)>
<!ELEMENT exe-highlight-type (#PCDATA)>

<!ELEMENT cleanup (execute+)>

<!ELEMENT variable-list (variable+)>
<!ELEMENT variable (#PCDATA)>
    <!ATTLIST variable key CDATA #REQUIRED>
    <!ATTLIST variable if CDATA "default">
    <!ATTLIST variable eval CDATA "n">

<!ELEMENT backrest-config (title, backrest-config-option+)>
    <!ATTLIST backrest-config host CDATA #REQUIRED>
    <!ATTLIST backrest-config owner CDATA "">
    <!ATTLIST backrest-config show CDATA "">
    <!ATTLIST backrest-config if CDATA "">
    <!ATTLIST backrest-config reset CDATA "">
    <!ATTLIST backrest-config file CDATA #REQUIRED>
<!ELEMENT backrest-config-option (#PCDATA)>
    <!ATTLIST backrest-config-option if CDATA "">
    <!ATTLIST backrest-config-option section CDATA #REQUIRED>
    <!ATTLIST backrest-config-option key CDATA #REQUIRED>
    <!ATTLIST backrest-config-option multi CDATA "n">
    <!ATTLIST backrest-config-option remove CDATA "n">

<!ELEMENT postgres-config (title, postgres-config-option+)>
    <!ATTLIST postgres-config host CDATA #REQUIRED>
    <!ATTLIST postgres-config file CDATA #REQUIRED>
    <!ATTLIST postgres-config if CDATA "">
    <!ATTLIST postgres-config show CDATA "">
<!ELEMENT postgres-config-option (#PCDATA)>
    <!ATTLIST postgres-config-option if CDATA "">
    <!ATTLIST postgres-config-option key CDATA #REQUIRED>

<!ELEMENT option-description EMPTY>
    <!ATTLIST option-description key CDATA #REQUIRED>

<!ELEMENT cmd-description EMPTY>
    <!ATTLIST cmd-description key CDATA #REQUIRED>

<!ELEMENT section (title?,
                   ((p|text|list|table|host-add|execute-list|backrest-config|postgres-config|cmd-description|sponsor-list|
                     option-description|code-block|block|section|admonition)*))>
    <!ATTLIST section id CDATA #REQUIRED>
    <!ATTLIST section if CDATA "">
    <!ATTLIST section depend CDATA "">
    <!ATTLIST section source CDATA "">
    <!ATTLIST section toc CDATA "">
<!ELEMENT title (#PCDATA|quote|b|i|bi|ul|ol|id|code|host|file|path|cmd|setting|exe|backrest|postgres|br-option|br-setting|
                 pg-option|pg-setting|link|user|proper)*>

<!ELEMENT block-define (
    ((p|list|table|host-add|execute-list|backrest-config|postgres-config|cmd-description|
      option-description|code-block|block|admonition)+|
    ((p|list)*, section+)|(p|list)*))>
    <!ATTLIST block-define id CDATA #REQUIRED>
    <!ATTLIST block-define if CDATA "">

<!ELEMENT block (block-variable-replace*)>
    <!ATTLIST block id CDATA #REQUIRED>
    <!ATTLIST block if CDATA "">
<!ELEMENT block-variable-replace (#PCDATA)>
    <!ATTLIST block-variable-replace key CDATA #REQUIRED>

<!ELEMENT default (#PCDATA)>
<!ELEMENT allow (#PCDATA)>
<!ELEMENT example (#PCDATA)>

<!ELEMENT sponsor-list (sponsor+)>

<!ELEMENT sponsor (#PCDATA)>
    <!ATTLIST sponsor img CDATA #REQUIRED>
    <!ATTLIST sponsor img-dark CDATA "">
    <!ATTLIST sponsor url CDATA #REQUIRED>
    <!ATTLIST sponsor width CDATA #REQUIRED>

<!ELEMENT contributor-list (contributor+)>

<!ELEMENT contributor (contributor-name-display, contributor-id*)>
    <!ATTLIST contributor id CDATA #REQUIRED>

<!ELEMENT contributor-name-display (#PCDATA)>
<!ELEMENT contributor-id (#PCDATA)>
    <!ATTLIST contributor-id type CDATA #REQUIRED>

<!ELEMENT release-list (release+)>

<!ELEMENT release (release-core-list?, release-doc-list?, release-test-list?)>
    <!ATTLIST release date CDATA #REQUIRED>
    <!ATTLIST release version CDATA #REQUIRED>
    <!ATTLIST release title CDATA #REQUIRED>

<!ELEMENT release-core-list (text?, release-bug-list?, release-feature-list?, release-improvement-list?, release-development-list?)>
<!ELEMENT release-test-list (text?, release-feature-list?, release-improvement-list?, release-development-list?)>
<!ELEMENT release-doc-list (text?, release-bug-list?, release-feature-list?, release-improvement-list?, release-development-list?)>

<!ELEMENT release-bug-list (release-item+)>
<!ELEMENT release-feature-list (release-item+)>
<!ELEMENT release-improvement-list (release-item+)>
<!ELEMENT release-development-list (release-item+)>

<!ELEMENT release-item (((github-issue*, github-pull-request*)|commit*), release-item-contributor-list?, p+)>

<!ELEMENT release-item-contributor-list (release-item-ideator*, release-item-contributor*, release-item-reviewer*)>

<!ELEMENT release-item-ideator (#PCDATA)>
    <!ATTLIST release-item-ideator id CDATA #REQUIRED>
<!ELEMENT release-item-contributor (#PCDATA)>
    <!ATTLIST release-item-contributor id CDATA #REQUIRED>
<!ELEMENT release-item-reviewer (#PCDATA)>
    <!ATTLIST release-item-reviewer id CDATA #REQUIRED>

<!ELEMENT github-issue EMPTY>
    <!ATTLIST github-issue id CDATA #REQUIRED>

<!ELEMENT github-pull-request EMPTY>
    <!ATTLIST github-pull-request id CDATA #REQUIRED>

<!ELEMENT commit (github-issue*, github-pull-request*)>
    <!ATTLIST commit type CDATA "">
    <!ATTLIST commit id CDATA "">
    <!ATTLIST commit subject CDATA #REQUIRED>

<!ELEMENT contribute (text)>
    <!ATTLIST contribute title CDATA #REQUIRED>

<!ELEMENT recognition (text)>
    <!ATTLIST recognition title CDATA #REQUIRED>

<!ELEMENT support (text)>
    <!ATTLIST support title CDATA #REQUIRED>

<!-- Host elements -->
<!ELEMENT host-define (#PCDATA)>
    <!ATTLIST host-define if CDATA "">
    <!ATTLIST host-define image CDATA #REQUIRED>
    <!ATTLIST host-define from CDATA #REQUIRED>
    <!ATTLIST host-define revision CDATA "0">

<!ELEMENT host-add (execute*)>
    <!ATTLIST host-add if CDATA "">
    <!ATTLIST host-add id CDATA "">
    <!ATTLIST host-add name CDATA #REQUIRED>
    <!ATTLIST host-add user CDATA #REQUIRED>
    <!ATTLIST host-add image CDATA #REQUIRED>
    <!ATTLIST host-add option CDATA "">
    <!ATTLIST host-add update-hosts CDATA "">
    <!ATTLIST host-add param CDATA "">
    <!ATTLIST host-add os CDATA "">
    <!ATTLIST host-add mount CDATA "">

<!-- Table elements -->
<!ELEMENT table (title?, table-header?, table-data)>
    <!ATTLIST title label CDATA "">

<!ELEMENT table-header (table-column+)>
    <!ATTLIST table-header width CDATA "">
<!ELEMENT table-column (#PCDATA|quote|b|i|id|code|host|file|path|cmd|setting|exe|backrest|postgres|br-option|
                        br-setting|pg-option|pg-setting|link|user|proper)*>
    <!ATTLIST table-column align CDATA "">
    <!ATTLIST table-column fill CDATA "">

<!ELEMENT table-data (table-row+)>
<!ELEMENT table-row (table-cell+)>
<!ELEMENT table-cell (#PCDATA|quote|b|i|ul|ol|id|code|code-block|host|file|path|cmd|setting|exe|backrest|postgres|br-option|
                      br-setting|pg-option|pg-setting|link|user|proper)*>

<!-- Formatted elements -->
<!-- admonition type can be note, important, warning, caution and tip -->
<!ELEMENT admonition ANY>
    <!ATTLIST admonition type CDATA #REQUIRED>
<!ELEMENT summary (#PCDATA|quote|b|i|ul|ol|id|code|code-block|host|file|path|cmd|setting|exe|backrest|postgres|br-option|
                   br-setting|pg-option|pg-setting|link|user|proper)*>
<!ELEMENT p ANY>
    <!ATTLIST p if CDATA "">
<!ELEMENT text (p|list|admonition|br)*>
<!ELEMENT i ANY>
<!ELEMENT b ANY>
<!ELEMENT br ANY>
<!ELEMENT list (list-item+)>
    <!ATTLIST list if CDATA "">
<!ELEMENT list-item ANY>
    <!ATTLIST list-item if CDATA "">
<!ELEMENT id (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT code-block (#PCDATA|exe)*>
    <!ATTLIST code-block title CDATA "">
    <!ATTLIST code-block type CDATA "">

<!ELEMENT host (#PCDATA)>
<!ELEMENT file (#PCDATA)>
<!ELEMENT path (#PCDATA)>
<!ELEMENT cmd (#PCDATA)>
<!ELEMENT user (#PCDATA)>
<!ELEMENT quote (#PCDATA)>
<!ELEMENT proper (#PCDATA)>
<!ELEMENT setting (#PCDATA)>
<!ELEMENT br-option (#PCDATA)>
<!ELEMENT br-setting (#PCDATA)>
<!ELEMENT pg-option (#PCDATA)>
<!ELEMENT pg-setting (#PCDATA)>
<!ELEMENT exe EMPTY>
<!ELEMENT backrest EMPTY>
<!ELEMENT postgres EMPTY>
<!ELEMENT link (#PCDATA)>
    <!ATTLIST link url CDATA "">
    <!ATTLIST link page CDATA "">
    <!ATTLIST link section CDATA "">

=== pgbackrest/pgbackrest/doc/src/build/help/help.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE doc SYSTEM "doc.dtd">
<doc>
    <config><config-section-list></config-section-list></config>

    <operation>
        <operation-general>
            <option-list>
                <option id="beta"><summary></summary><text><p></p></text></option>
                <option id="cmd"><summary></summary><text><p></p></text></option>
                <option id="config"><summary></summary><text><p></p></text></option>
                <option id="config-path"><summary></summary><text><p></p></text></option>
                <option id="config-include-path"><summary></summary><text><p></p></text></option>
                <option id="pg"><summary></summary><text><p></p></text></option>
                <option id="pg-path"><summary></summary><text><p></p></text></option>
                <option id="compress-level-network"><summary></summary><text><p></p></text></option>
                <option id="job-retry"><summary></summary><text><p></p></text></option>
                <option id="job-retry-interval"><summary></summary><text><p></p></text></option>
                <option id="lock"><summary></summary><text><p></p></text></option>
                <option id="log-level-file"><summary></summary><text><p></p></text></option>
                <option id="log-level-stderr"><summary></summary><text><p></p></text></option>
                <option id="repo"><summary></summary><text><p></p></text></option>
                <option id="repo-type"><summary></summary><text><p></p></text></option>
                <option id="spool-path"><summary></summary><text><p></p></text></option>
                <option id="stanza"><summary></summary><text><p></p></text></option>

                <option id="buffer-size">
                    <summary>Buffer size for I/O operations.</summary>

                    <text>
                        <p>Buffer size used for copy, compress, encrypt, and other operations. The number of buffers used depends on options and each operation may use additional memory, e.g. <id>gz</id> compression may use an additional 256KiB of memory.</p>

                        <p>Allowed values are <id>16KiB</id>, <id>32KiB</id>, <id>64KiB</id>, <id>128KiB</id>, <id>256KiB</id>, <id>512KiB</id>, and <id>1MiB</id>.</p>
                    </text>

                    <example>1MiB</example>
                </option>

                <option id="log-level">
                    <summary>Level for harness logging.</summary>

                    <text>
                        <p>Log level for the test harness (as opposed to the test being run).</p>

                        <p>The following log levels are supported:</p>

                        <list>
                            <list-item><id>off</id> - No logging at all (not recommended)</list-item>
                            <list-item><id>error</id> - Log only errors</list-item>
                            <list-item><id>warn</id> - Log warnings and errors</list-item>
                            <list-item><id>info</id> - Log info, warnings, and errors</list-item>
                            <list-item><id>detail</id> - Log detail, info, warnings, and errors</list-item>
                            <list-item><id>debug</id> - Log debug, detail, info, warnings, and errors</list-item>
                            <list-item><id>trace</id> - Log trace (very verbose debugging), debug, info, warnings, and errors</list-item>
                        </list>
                    </text>

                    <example>error</example>
                </option>

                <option id="log-timestamp">
                    <summary>Enable timestamp in logging.</summary>

                    <text>
                        <p>Enables the timestamp in console and file logging. This option is disabled in special situations such as generating documentation.</p>
                    </text>

                    <example>n</example>
                </option>

                <option id="neutral-umask">
                    <summary>Use a neutral umask.</summary>

                    <text>
                        <p>Sets the umask to 0000 so modes are created in a sensible way. The default directory mode is 0750 and default file mode is 0640.</p>

                        <p>To use the executing user's umask instead specify <setting>neutral-umask=n</setting> in the config file or <setting>--no-neutral-umask</setting> on the command line.</p>
                    </text>

                    <example>n</example>
                </option>

                <option id="repo-path">
                    <summary>Path to code repository.</summary>

                    <text>
                        <p>Path to the original code repository.</p>
                    </text>

                    <example>/path/to/pgbackrest</example>
                </option>
            </option-list>
        </operation-general>

        <command-list>
            <command id="help">
                <summary>Get help.</summary>

                <text>
                    <p>Three levels of help are provided. If no command is specified then general help will be displayed. If a command is specified (e.g. <cmd>doc-pgbackrest help build</cmd>) then a full description of the command will be displayed along with a list of valid options. If an option is specified in addition to a command (e.g. <cmd>doc-pgbackrest help build repo-path</cmd>) then a full description of the option as it applies to the command will be displayed.</p>
                </text>

                <option-list>
                    <option id="help" name="Display Help">
                        <summary>Display help.</summary>

                        <text>
                            <p>Displays help even if the <cmd>help</cmd> command is not specified and overrides the <br-option>--version</br-option> option.</p>
                        </text>

                        <example>y</example>
                    </option>

                    <option id="version" name="Display Version">
                        <summary>Display version.</summary>

                        <text>
                            <p>Displays version even if the <cmd>version</cmd> or <cmd>help</cmd> command is not specified.</p>
                        </text>

                        <example>y</example>
                    </option>
                </option-list>
            </command>

            <!-- Noop command holds options that must be defined but we don't need -->
            <command id="noop"><summary></summary><text><p></p></text></command>

            <command id="build">
                <summary>Build documentation.</summary>

                <text>
                    <p>Build the specified documentation module.</p>
                </text>

                <option-list>
                    <option id="var" name="Set variable">
                        <summary>Set variable.</summary>

                        <text>
                            <p>This will override the variable as defined in the XML.</p>
                        </text>

                        <example>os-type=rhel</example>
                    </option>
                </option-list>
            </command>

            <command id="version">
                <summary>Get version.</summary>

                <text>
                    <p>Displays installed <backrest/> version.</p>
                </text>

                <option-list>
                    <option id="output" name="Output">
                        <summary>Output type.</summary>

                        <text>
                            <p>The following output formats are supported:</p>
                            <list>
                                <list-item><id>text</id> - Display the installed <backrest/> version as text.</list-item>
                                <list-item><id>num</id> - Display the installed <backrest/> version as an integer.</list-item>
                            </list>
                        </text>

                        <example>num</example>
                    </option>
                </option-list>
            </command>
        </command-list>
    </operation>
</doc>

=== pgbackrest/pgbackrest/doc/xml/documentation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE doc SYSTEM "doc.dtd">
<doc title="{[project]}" subtitle="Building Documentation" toc="y">
    <description>Building {[project]} Documentation</description>

    <section id="general">
        <title>General Builds</title>

        <p>The <backrest/> documentation can output a variety of formats and target several platforms and <postgres/> versions.</p>

        <p>This will build all documentation with defaults:</p>

        <code-block type="bash">
./doc.pl
        </code-block>

        <p>The user guide can be built for <id>rhel</id> and <id>debian</id>. This will build the HTML user guide for RHEL:</p>

        <code-block type="bash">
./doc.pl --out=html --include=user-guide --var=os-type=rhel
        </code-block>

        <p>Documentation generation will build a cache of all executed statements and use the cache to build the documentation quickly if no executed statements have changed.  This makes proofing text-only edits very fast, but sometimes it is useful to do a full build without using the cache:</p>

        <code-block type="bash">
./doc.pl --out=html --include=user-guide --var=os-type=rhel --no-cache
        </code-block>

        <p>Each <id>os-type</id> has a default container image that will be used as a base for creating hosts but it may be useful to change the image.</p>

        <code-block type="bash">
./doc.pl --out=html --include=user-guide --var=os-type=debian --var=os-image=debian:9
./doc.pl --out=html --include=user-guide --var=os-type=rhel --var=os-image=centos:7
        </code-block>

        <p>The following is a sample RHEL 7 configuration that can be used for building the documentation.</p>

        <code-block type="bash">
# Install docker
sudo yum install -y yum-utils device-mapper-persistent-data lvm2
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum install -y docker-ce
sudo systemctl start docker

# Install tools
sudo yum install -y git wget

# Install latex (for building PDF)
sudo yum install -y texlive texlive-titlesec texlive-sectsty texlive-framed texlive-epstopdf ghostscript

# Install Perl modules via CPAN that do not have packages
sudo yum install -y yum cpanminus
sudo yum groupinstall -y "Development Tools" "Development Libraries"
sudo cpanm install --force XML::Checker::Parser

# Add documentation test user
sudo groupadd test
sudo adduser -gtest -n testdoc
sudo usermod -aG docker testdoc
        </code-block>
    </section>

    <section id="package">
        <title>Building with Packages</title>

        <p>A user-specified package can be used when building the documentation.  Since the documentation exercises most <backrest/> functionality this is a great way to smoke-test packages.</p>

        <p>The package must be located within the <backrest/> repo and the specified path should be relative to the repository base.  <path>test/package</path> is a good default path to use.</p>

        <p>Ubuntu 16.04:</p>

        <code-block type="bash">
./doc.pl --out=html --include=user-guide --no-cache --var=os-type=debian --var=os-image=ubuntu:16.04 --var=package=test/package/pgbackrest_2.08-0_amd64.deb
        </code-block>

        <p>RHEL 7:</p>

        <code-block type="bash">
./doc.pl --out=html --include=user-guide --no-cache --var=os-type=rhel --var=os-image=centos:7  --var=package=test/package/pgbackrest-2.08-1.el7.x86_64.rpm
        </code-block>

        <p>RHEL 8:</p>

        <code-block type="bash">
./doc.pl --out=html --include=user-guide --no-cache --var=os-type=rhel --var=os-image=centos:8 --var=package=test/package/pgbackrest-2.08-1.el8.x86_64.rpm
        </code-block>

        <p>Packages can be built with <file>test.pl</file> using the following configuration on top of the configuration given for building the documentation.</p>

        <code-block type="bash">
# Install recent git
sudo yum remove -y git
sudo yum install -y https://centos7.iuscommunity.org/ius-release.rpm
sudo yum install -y git2u-all

# Install Perl modules
sudo yum install -y perl-ExtUtils-ParseXS perl-ExtUtils-Embed perl-ExtUtils-MakeMaker perl-YAML-LibYAML

# Install dev libraries
sudo yum install -y libxml2-devel openssl-devel

# Add test user with sudo privileges
sudo adduser -gtest -n test
sudo usermod -aG docker test
sudo chmod 750 /home/test

sudo echo 'test ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/pgbackrest

# Add pgbackrest user required by tests
sudo adduser -gtest -n pgbackrest
        </code-block>
    </section>
</doc>

=== pgbackrest/pgbackrest/doc/xml/distribution.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE doc SYSTEM "doc.dtd">
<doc title="{[project]} Distribution" toc="n">
    <description>{[project]} distribution build and test instructions.</description>

    <!-- ======================================================================================================================= -->
    <section id="overview">
        <title>Overview</title>

        <p>This is a <backrest/> build distribution. Unlike a checkout of the <link url="{[github-url-base]}">git repository</link>, it ships the generated source and the rendered documentation pre-built, so <backrest/> can be built and installed without the code generation or the documentation tooling.</p>

        <p>See <link url="{[backrest-url-base]}">{[backrest-url-base]}</link> for complete documentation.</p>
    </section>

    <!-- ======================================================================================================================= -->
    <section id="contents">
        <title>Contents</title>

        <list>
            <list-item><file>src</file> -- <backrest/> source, including the pre-generated <file>*.auto.c.inc</file> files</list-item>
            <list-item><file>doc/man</file> -- command reference</list-item>
            <list-item><file>doc/html</file> -- HTML documentation</list-item>
            <list-item><file>test</file> -- smoke test to verify the build</list-item>
            <list-item><file>meson.build</file>, <file>meson_options.txt</file> -- build configuration</list-item>
            <list-item><file>LICENSE</file></list-item>
        </list>
    </section>

    <!-- ======================================================================================================================= -->
    <section id="build">
        <title>Build</title>

        <p><backrest/> builds with meson and ninja. The required libraries are libpq, OpenSSL (&gt;= 1.1.1), libxml2, lz4, bz2, and zlib; zstd, libssh2 (for SFTP), and libsystemd are optional. For example, on Debian/Ubuntu:</p>

        <code-block>
apt-get install meson gcc pkg-config libpq-dev libssl-dev libxml2-dev \
    liblz4-dev libzstd-dev libbz2-dev libz-dev libssh2-1-dev libsystemd-dev
        </code-block>

        <p>Then configure, build, and install:</p>

        <code-block>
meson setup build .
ninja -C build
meson install -C build
        </code-block>

        <p>The <file>pgbackrest</file> binary is built at <file>build/src/pgbackrest</file>.</p>
    </section>

    <!-- ======================================================================================================================= -->
    <section id="test">
        <title>Test</title>

        <p>A smoke test is included to verify that the build works. It finds each <postgres/> installation on the system and runs the newly-built <file>pgbackrest</file> through a backup and restore cycle against every supported version found: create a cluster, configure archiving, create the stanza, check, back up, restore, and verify that the restored data matches. Versions that <backrest/> does not support are reported and skipped. The test requires nothing beyond the build environment and <postgres/> -- no additional Python packages.</p>

        <p>Run it with meson after building:</p>

        <code-block>
meson test -C build --suite smoke
        </code-block>

        <p>Add <code>-v</code> to stream the output of each step as it runs:</p>

        <code-block>
meson test -C build --suite smoke -v
        </code-block>

        <p><postgres/> is searched for in the standard packaging paths:</p>

        <list>
            <list-item><file>/usr/lib/postgresql/&lt;version&gt;/bin</file> (Debian/Ubuntu)</list-item>
            <list-item><file>/usr/pgsql-&lt;version&gt;/bin</file> (RHEL)</list-item>
            <list-item><file>/usr/libexec/postgresql&lt;version&gt;</file> (Alpine)</list-item>
            <list-item><file>/usr/bin</file></list-item>
        </list>

        <p>Each version is tested in a temporary directory with its own repository and a private unix socket, so a running <postgres/> cluster is not disturbed. The test fails when there is no <postgres/> to test against, since a test that silently does nothing does not verify the build. Since <postgres/> will not run as root, running the test as root drops to the <code>postgres</code> user and fails if that user does not exist.</p>

        <p>The test can also be run directly, which allows the defaults to be overridden:</p>

        <code-block>
python3 test/smoke.py --pgbackrest build/src/pgbackrest
        </code-block>

        <p>Useful options are <code>--pg-bin-path</code> to search an additional path for <postgres/>, <code>--version</code> to test only a specific version, and <code>--user</code> to select the user to drop to when running as root. Use <code>--help</code> for the complete list.</p>
    </section>

    <!-- ======================================================================================================================= -->
    <section id="documentation">
        <title>Documentation</title>

        <p>The rendered documentation is in <file>doc</file>: the command reference in <file>doc/man</file> and the HTML documentation in <file>doc/html</file>.</p>

        <p>Two user guides are provided, Debian/Ubuntu and RHEL/Rocky/Alma. If only one user guide is required, replace <file>user-guide-index.html</file> with the desired user guide. For example, to keep only the Debian/Ubuntu user guide:</p>

        <code-block>
mv user-guide.html user-guide-index.html
rm user-guide-rhel.html
        </code-block>
    </section>
</doc>
