=== pgbackrest/pgbackrest/doc/doc.dtd
<!ELEMENT doc (intro, install, operation, config, release, recognition)>
	<!ATTLIST doc title CDATA #REQUIRED>
	<!ATTLIST doc subtitle CDATA #REQUIRED>

<!ELEMENT intro (text)>

<!ELEMENT install (text, install-system-list)>
	<!ATTLIST install title CDATA #REQUIRED>

<!ELEMENT install-system-list (text?, install-system+)>

<!ELEMENT install-system (text)>
	<!ATTLIST install-system title CDATA #REQUIRED>

<!ELEMENT operation (text?, operation-general, command-list)>
	<!ATTLIST operation title CDATA #REQUIRED>

<!ELEMENT operation-general (text, option-list)>
	<!ATTLIST operation-general title CDATA #REQUIRED>

<!ELEMENT command-list (text?, command+)>
	<!ATTLIST command-list title CDATA #REQUIRED>

<!ELEMENT command (text, option-list?, command-example-list)>
	<!ATTLIST command id CDATA #REQUIRED>

<!ELEMENT command-example-list (text?, command-example+)>
	<!ATTLIST command-example-list title CDATA "Examples">

<!ELEMENT command-example (text)>
	<!ATTLIST command-example title CDATA "Example">

<!ELEMENT option-list (option+)>

<!ELEMENT option (text, example?)>
	<!ATTLIST option id CDATA #REQUIRED>

<!ELEMENT config (text, config-example-list, config-section-list)>
	<!ATTLIST config title CDATA #REQUIRED>

<!ELEMENT config-example-list (text?, config-example+)>
	<!ATTLIST config-example-list title CDATA #REQUIRED>

<!ELEMENT config-example (text)>
	<!ATTLIST config-example title CDATA #REQUIRED>

<!ELEMENT config-section-list (text?, config-section+)>
	<!ATTLIST config-section-list title CDATA #REQUIRED>

<!ELEMENT config-section (text, config-key-list?)>
	<!ATTLIST config-section id CDATA #REQUIRED>

<!ELEMENT config-key-list (config-key+)>

<!ELEMENT config-key (text, default?, allow?, example)>
	<!ATTLIST config-key id CDATA #REQUIRED>

<!ELEMENT default (#PCDATA)>
<!ELEMENT allow (#PCDATA)>
<!ELEMENT example (#PCDATA)>

<!ELEMENT release (text?, release-version-list)>
	<!ATTLIST release title CDATA #REQUIRED>

<!ELEMENT release-version-list (release-version+)>

<!ELEMENT release-version (text?, release-feature-bullet-list)>
	<!ATTLIST release-version version CDATA #REQUIRED>
	<!ATTLIST release-version title CDATA #REQUIRED>

<!ELEMENT release-feature-bullet-list (release-feature+)>

<!ELEMENT release-feature (text)>

<!ELEMENT recognition (text)>
	<!ATTLIST recognition title CDATA #REQUIRED>

<!ELEMENT text (#PCDATA|b|i|bi|ul|ol|id|code|code-block|file|path|cmd|param|setting|backrest|postgres)*>
<!ELEMENT i (#PCDATA)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT bi (#PCDATA)>
<!ELEMENT ul (li+)>
<!ELEMENT ol (li+)>
<!ELEMENT li (#PCDATA|b|i|bi|ul|ol|id|code|code-block|file|path|cmd|param|setting|backrest|postgres)*>
<!ELEMENT id (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT code-block (#PCDATA)>
<!ELEMENT file (#PCDATA)>
<!ELEMENT path (#PCDATA)>
<!ELEMENT cmd (#PCDATA)>
<!ELEMENT param (#PCDATA)>
<!ELEMENT setting (#PCDATA)>
<!ELEMENT backrest EMPTY>
<!ELEMENT postgres EMPTY>

=== pgbackrest/pgbackrest/doc/xml/change-log.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE doc SYSTEM "doc.dtd">
<doc title="Change Log">
    <intro>
        <text></text>
    </intro>

    <changelog>
        <changelog-release date="XXXX-XX-XX" version="0.90" title="UNDER DEVELOPMENT">
            <release-feature-bullet-list>
                <release-feature>
                    <text>Fixed an issue where longer-running backups/restores would timeout when remote and threaded.  Keepalives are now used to make sure the remote for the main process does not timeout while the thread remotes do all the work.  The error messages for timeouts was also improved to make debugging easier.</text>
                </release-feature>
                <release-feature>
                    <text>Allow restores to be performed on a read-only repository by using <setting>--no-lock</setting> and <setting>--log-level-file=off</setting>.  The <setting>--no-lock</setting> option can only be used with restores.</text>
                </release-feature>
            </release-feature-bullet-list>
        </changelog-release>

        <changelog-release date="2015-11-22" version="0.88" title="Documentation and Minor Bug Fixes">
            <release-feature-bullet-list>
                <release-feature>
                    <text>Added documentation in the user guide for delta restores, expiration, dedicated backup hosts, starting and stopping <backrest/>, and replication.</text>
                </release-feature>
                <release-feature>
                    <text>Fixed an issue where the <cmd>start</cmd>/<cmd>stop</cmd> commands required the <setting>--config</setting> option.</text>
                </release-feature>
                <release-feature>
                    <text>Fixed an issue where log files were being overwritten instead of appended.</text>
                </release-feature>
                <release-feature>
                    <text>Fixed an issue where <setting>backup-user</setting> was not optional.</text>
                </release-feature>
                <release-feature>
                    <text>Symlinks are no longer created in backup directories in the repository.  These symlinks could point virtually anywhere and potentially be dangerous.  Symlinks are still recreated during a restore.</text>
                </release-feature>
                <release-feature>
                    <text>Added better messaging for backup expiration.  Full and differential backup expirations are logged on a single line along with a list of all dependent backups expired.</text>
                </release-feature>
                <release-feature>
                    <text>Archive retention is automatically set to full backup retention if not explicitly configured.</text>
                </release-feature>
            </release-feature-bullet-list>
        </changelog-release>

        <changelog-release date="2015-10-28" version="0.87" title="Website and User Guide">
            <release-feature-bullet-list>
                <release-feature>
                    <text>Added a new user guide that covers <backrest/> basics and some advanced topics including PITR.  Much more to come, but it's a start.</text>
                </release-feature>
                <release-feature>
                    <text>The website, markdown, and command-line help are now all generated from the same XML source.</text>
                </release-feature>
                <release-feature>
                    <text>The <file>backup_label.old</file> and <file>recovery.done</file> files are now excluded from backups.</text>
                </release-feature>
            </release-feature-bullet-list>
        </changelog-release>

        <changelog-release date="2015-10-08" version="0.85" title="Start/Stop Commands and Minor Bug Fixes">
            <release-feature-bullet-list>
                <release-feature>
                    <text>Added new feature to allow all <backrest/> operations to be stopped or started using the <cmd>stop</cmd> and <cmd>start</cmd> commands.  This prevents any <backrest/> processes from running on a system where <postgres/> is shutdown or the system needs to be quiesced for some reason.</text>
                </release-feature>
                <release-feature>
                    <text>Removed dependency on <code>IO::String</code> module.</text>
                </release-feature>
                <release-feature>
                    <text>Fixed an issue where an error could be returned after a backup or restore completely successfully.</text>
                </release-feature>
                <release-feature>
                    <text>Fixed an issue where a resume would fail if temp files were left in the root backup directory when the backup failed.  This scenario was likely if the backup process got terminated during the copy phase.</text>
                </release-feature>
                <release-feature>
                    <text>Experimental support for <postgres/> 9.5 beta1.  This may break when the control version or WAL magic changes in future versions but will be updated in each <backrest/> release to keep pace.  All regression tests pass except for <setting>--target-resume</setting> tests (this functionality has changed in 9.5) and there is no testing yet for <file>.partial</file> WAL segments.</text>
                </release-feature>
            </release-feature-bullet-list>
        </changelog-release>

        <changelog-release date="2015-09-14" version="0.82" title="Refactoring, Command-line Help, and Minor Bug Fixes">
            <release-feature-bullet-list>
                <release-feature>
                    <text>Fixed an issue where resumed compressed backups were not preserving existing files.</text>
                </release-feature>
                <release-feature>
                    <text>Fixed an issue where resume and incr/diff would not ensure that the prior backup had the same compression and hardlink settings.</text>
                </release-feature>
                <release-feature>
                    <text>Fixed an issue where a cold backup using <setting>--no-start-stop</setting> could be started on a running <postgres/> cluster without <setting>--force</setting> specified.</text>
                </release-feature>
                <release-feature>
                    <text>Fixed an issue where a thread could be started even when none were requested.</text>
                </release-feature>
                <release-feature>
                    <text>Fixed an issue where the <backrest/> version number was not being updated in <file>backup.info</file> and <file>archive.info</file> after an upgrade/downgrade.</text>
                </release-feature>
                <release-feature>
                    <text>Fixed an issue where the <cmd>info</cmd> command was throwing an exception when the repository contained no stanzas.  <i>Reported by Stephen Frost</i>.</text>
                </release-feature>
                <release-feature>
                    <text>Fixed an issue where the <postgres/> <code>pg_stop_backup()</code> NOTICEs were being output to stderr.  <i>Reported by Stephen Frost</i>.</text>
                </release-feature>
                <release-feature>
                    <text>Renamed <setting>recovery-setting</setting> option and section to <setting>recovery-option</setting> to be more consistent with <backrest/> naming conventions.</text>
                </release-feature>
                <release-feature>
                    <text>Command-line help is now extracted from the same XML source that is used for the other documentation and includes much more detail.</text>
                </release-feature>
                <release-feature>
                    <text>Code cleanup and refactoring to standardize on patterns that have evolved over time.</text>
                </release-feature>
                <release-feature>
                    <text>Added dynamic module loading to speed up commands, especially asynchronous archiving.</text>
                </release-feature>
                <release-feature>
                    <text>Expiration tests are now synthetic rather than based on actual backups.  This will allow development of more advanced expiration features.</text>
                </release-feature>
                <release-feature>
                    <text>Experimental support for <postgres/> 9.5 alpha2.  This may break when the control version or WAL magic changes in future versions but will be updated in each <backrest/> release to keep pace.  All regression tests pass except for <setting>--target-resume</setting> tests (this functionality has changed in 9.5) and there is no testing yet for <file>.partial</file> WAL segments.</text>
                </release-feature>
            </release-feature-bullet-list>
        </changelog-release>

        <changelog-release date="2015-08-09" version="0.80" title="DBI Support, Stability, and Convenience Features">
            <release-feature-bullet-list>
                <release-feature>
                    <text>Fixed an issue that caused the formatted timestamp for both the oldest and newest backups to be reported as the current time by the <cmd>info</cmd> command.  Only <id>text</id> output was affected -- <id>json</id> output reported the correct epoch values.  <i>Reported by Michael Renner</i>.</text>
                </release-feature>
                <release-feature>
                    <text>Fixed protocol issue that was preventing ssh errors (especially on connection) from being logged.</text>
                </release-feature>
                <release-feature>
